before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: GCh/z4/E+OaG32/dS5nUiT5q4tPyrVE25hKl784B5Fnt/dPXWgJFKuqhx7sXv6hgFo+tepxczMdHHLJ2UFaqUV2b4HPWGI+BI20Asnt2uHV6lekAgSPWu1EqAphIgb4Bit6yZTBeHEZmixqyFTlMqFq5xZGU9Af4wgcFD1lL2ph3UuF6SyUprnoeLNE+W3HgPTv9rzXv1Vd4H3Zst7sBhLWdumdUlcX0Jv5XcqfKgff7qanu9N+CIFmP/0tKM9iBTKDfCz9BOxEJGuyqe4EN/SV4aQaVCPAj3T0v9mpLdZWEI5P8dHUrpO5CD8f1+b0Qpai+LdktwkrDVD/MHl2idDn0vEZyO5QPAb6fjnCdtmzAW4LP2JhDuwbNpk7bNLExxI4xHM6sxsOUunkjLqCe+xE4Jd4uipPafUOnkHow2CvBp+y0PeDZDhvvetoHO+MwpLfEfFlPiZRd2zvXmSsAvnDN7Se/gEMFZWGoTIY/1Ls7PBWi+b5VAPGVhbA8SnKhnUL9rGyt1ZFAjFPMIrsdhwhcfXxLNsq+RTWdXJTrAKIBUbrsIvQdNxayFMnF9TSSR2ktXb9itiqNj1+bxLty2T5CZqnTl+JGYTRvlYlG7IBPTBQALOaOGxcI0awSLX22Rg7NQtbpHgAsGgxvdv7qDETAuqgHz6/cEn2g+bS0Zc8= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
